// AUTO-GENERATED from the binder-insert PDF — the authoritative card list.
// For real art later: drop images in public/cards/<set>/<number>.png and set `image`.

import type { Card } from "./types";

export const abyssEyeCards: Card[] = [
  { number: 1, name: "Tropius", badge: "C", label: "Pok\u00e9mon \u00b7 Common", holoTier: 0, secret: false },
  { number: 2, name: "Grubbin", badge: "C", label: "Pok\u00e9mon \u00b7 Common", holoTier: 0, secret: false },
  { number: 3, name: "Fomantis", badge: "C", label: "Pok\u00e9mon \u00b7 Common", holoTier: 0, secret: false },
  { number: 4, name: "Lurantis ex", badge: "RR", label: "Pok\u00e9mon ex \u00b7 Double Rare", holoTier: 1, secret: false },
  { number: 5, name: "Sinistea", badge: "C", label: "Pok\u00e9mon \u00b7 Common", holoTier: 0, secret: false },
  { number: 6, name: "Polteageist", badge: "U", label: "Pok\u00e9mon \u00b7 Uncommon", holoTier: 0, secret: false },
  { number: 7, name: "Heatran", badge: "U", label: "Pok\u00e9mon \u00b7 Uncommon", holoTier: 0, secret: false },
  { number: 8, name: "Sizzlipede", badge: "C", label: "Pok\u00e9mon \u00b7 Common", holoTier: 0, secret: false },
  { number: 9, name: "Centiskorch", badge: "C", label: "Pok\u00e9mon \u00b7 Common", holoTier: 0, secret: false },
  { number: 10, name: "Charcadet", badge: "C", label: "Pok\u00e9mon \u00b7 Common", holoTier: 0, secret: false },
  { number: 11, name: "Armarouge", badge: "R", label: "Pok\u00e9mon \u00b7 Rare", holoTier: 1, secret: false },
  { number: 12, name: "Goldeen", badge: "C", label: "Pok\u00e9mon \u00b7 Common", holoTier: 0, secret: false },
  { number: 13, name: "Seaking", badge: "U", label: "Pok\u00e9mon \u00b7 Uncommon", holoTier: 0, secret: false },
  { number: 14, name: "Wailmer", badge: "C", label: "Pok\u00e9mon \u00b7 Common", holoTier: 0, secret: false },
  { number: 15, name: "Wailord ex", badge: "RR", label: "Pok\u00e9mon ex \u00b7 Double Rare", holoTier: 1, secret: false },
  { number: 16, name: "Relicanth", badge: "U", label: "Pok\u00e9mon \u00b7 Uncommon", holoTier: 0, secret: false },
  { number: 17, name: "Popplio", badge: "C", label: "Pok\u00e9mon \u00b7 Common", holoTier: 0, secret: false },
  { number: 18, name: "Brionne", badge: "C", label: "Pok\u00e9mon \u00b7 Common", holoTier: 0, secret: false },
  { number: 19, name: "Primarina", badge: "R", label: "Pok\u00e9mon \u00b7 Rare", holoTier: 1, secret: false },
  { number: 20, name: "Finizen", badge: "C", label: "Pok\u00e9mon \u00b7 Common", holoTier: 0, secret: false },
  { number: 21, name: "Palafin", badge: "U", label: "Pok\u00e9mon \u00b7 Uncommon", holoTier: 0, secret: false },
  { number: 22, name: "Electrike", badge: "C", label: "Pok\u00e9mon \u00b7 Common", holoTier: 0, secret: false },
  { number: 23, name: "Manectric", badge: "U", label: "Pok\u00e9mon \u00b7 Uncommon", holoTier: 0, secret: false },
  { number: 24, name: "Charjabug", badge: "C", label: "Pok\u00e9mon \u00b7 Common", holoTier: 0, secret: false },
  { number: 25, name: "Vikavolt", badge: "U", label: "Pok\u00e9mon \u00b7 Uncommon", holoTier: 0, secret: false },
  { number: 26, name: "Mega Zeraora ex", badge: "RR", label: "Mega ex \u00b7 Double Rare", holoTier: 1, secret: false },
  { number: 27, name: "Miraidon", badge: "U", label: "Pok\u00e9mon \u00b7 Uncommon", holoTier: 0, secret: false },
  { number: 28, name: "Slowpoke", badge: "C", label: "Pok\u00e9mon \u00b7 Common", holoTier: 0, secret: false },
  { number: 29, name: "Slowbro", badge: "U", label: "Pok\u00e9mon \u00b7 Uncommon", holoTier: 0, secret: false },
  { number: 30, name: "Jynx", badge: "C", label: "Pok\u00e9mon \u00b7 Common", holoTier: 0, secret: false },
  { number: 31, name: "Shuppet", badge: "C", label: "Pok\u00e9mon \u00b7 Common", holoTier: 0, secret: false },
  { number: 32, name: "Banette", badge: "U", label: "Pok\u00e9mon \u00b7 Uncommon", holoTier: 0, secret: false },
  { number: 33, name: "Spiritomb", badge: "R", label: "Pok\u00e9mon \u00b7 Rare", holoTier: 1, secret: false },
  { number: 34, name: "Litwick", badge: "C", label: "Pok\u00e9mon \u00b7 Common", holoTier: 0, secret: false },
  { number: 35, name: "Lampent", badge: "C", label: "Pok\u00e9mon \u00b7 Common", holoTier: 0, secret: false },
  { number: 36, name: "Mega Chandelure ex", badge: "RR", label: "Mega ex \u00b7 Double Rare", holoTier: 1, secret: false },
  { number: 37, name: "Dhelmise", badge: "U", label: "Pok\u00e9mon \u00b7 Uncommon", holoTier: 0, secret: false },
  { number: 38, name: "Marshadow", badge: "U", label: "Pok\u00e9mon \u00b7 Uncommon", holoTier: 0, secret: false },
  { number: 39, name: "Annihilape", badge: "U", label: "Pok\u00e9mon \u00b7 Uncommon", holoTier: 0, secret: false },
  { number: 40, name: "Mankey", badge: "C", label: "Pok\u00e9mon \u00b7 Common", holoTier: 0, secret: false },
  { number: 41, name: "Primeape", badge: "C", label: "Pok\u00e9mon \u00b7 Common", holoTier: 0, secret: false },
  { number: 42, name: "Cranidos", badge: "C", label: "Pok\u00e9mon \u00b7 Common", holoTier: 0, secret: false },
  { number: 43, name: "Rampardos ex", badge: "RR", label: "Pok\u00e9mon ex \u00b7 Double Rare", holoTier: 1, secret: false },
  { number: 44, name: "Drilbur", badge: "C", label: "Pok\u00e9mon \u00b7 Common", holoTier: 0, secret: false },
  { number: 45, name: "Koraidon", badge: "U", label: "Pok\u00e9mon \u00b7 Uncommon", holoTier: 0, secret: false },
  { number: 46, name: "Mega Darkrai ex", badge: "RR", label: "Mega ex \u00b7 Double Rare", holoTier: 1, secret: false },
  { number: 47, name: "Vullaby", badge: "C", label: "Pok\u00e9mon \u00b7 Common", holoTier: 0, secret: false },
  { number: 48, name: "Mandibuzz", badge: "C", label: "Pok\u00e9mon \u00b7 Common", holoTier: 0, secret: false },
  { number: 49, name: "Inkay", badge: "C", label: "Pok\u00e9mon \u00b7 Common", holoTier: 0, secret: false },
  { number: 50, name: "Malamar", badge: "U", label: "Pok\u00e9mon \u00b7 Uncommon", holoTier: 0, secret: false },
  { number: 51, name: "Nickit", badge: "C", label: "Pok\u00e9mon \u00b7 Common", holoTier: 0, secret: false },
  { number: 52, name: "Thievul", badge: "U", label: "Pok\u00e9mon \u00b7 Uncommon", holoTier: 0, secret: false },
  { number: 53, name: "Morpeko ex", badge: "RR", label: "Pok\u00e9mon ex \u00b7 Double Rare", holoTier: 1, secret: false },
  { number: 54, name: "Zarude", badge: "U", label: "Pok\u00e9mon \u00b7 Uncommon", holoTier: 0, secret: false },
  { number: 55, name: "Maschiff", badge: "C", label: "Pok\u00e9mon \u00b7 Common", holoTier: 0, secret: false },
  { number: 56, name: "Mabosstiff", badge: "C", label: "Pok\u00e9mon \u00b7 Common", holoTier: 0, secret: false },
  { number: 57, name: "Chi-Yu", badge: "R", label: "Pok\u00e9mon \u00b7 Rare", holoTier: 1, secret: false },
  { number: 58, name: "Skarmory", badge: "C", label: "Pok\u00e9mon \u00b7 Common", holoTier: 0, secret: false },
  { number: 59, name: "Shieldon", badge: "C", label: "Pok\u00e9mon \u00b7 Common", holoTier: 0, secret: false },
  { number: 60, name: "Bastiodon", badge: "R", label: "Pok\u00e9mon \u00b7 Rare", holoTier: 1, secret: false },
  { number: 61, name: "Bronzor", badge: "C", label: "Pok\u00e9mon \u00b7 Common", holoTier: 0, secret: false },
  { number: 62, name: "Bronzong", badge: "U", label: "Pok\u00e9mon \u00b7 Uncommon", holoTier: 0, secret: false },
  { number: 63, name: "Mega Excadrill ex", badge: "RR", label: "Mega ex \u00b7 Double Rare", holoTier: 1, secret: false },
  { number: 64, name: "Pikipek", badge: "C", label: "Pok\u00e9mon \u00b7 Common", holoTier: 0, secret: false },
  { number: 65, name: "Trumbeak", badge: "C", label: "Pok\u00e9mon \u00b7 Common", holoTier: 0, secret: false },
  { number: 66, name: "Toucannon", badge: "U", label: "Pok\u00e9mon \u00b7 Uncommon", holoTier: 0, secret: false },
  { number: 67, name: "Type: Null", badge: "C", label: "Pok\u00e9mon \u00b7 Common", holoTier: 0, secret: false },
  { number: 68, name: "Silvally", badge: "R", label: "Pok\u00e9mon \u00b7 Rare", holoTier: 1, secret: false },
  { number: 69, name: "Bombirdier", badge: "C", label: "Pok\u00e9mon \u00b7 Common", holoTier: 0, secret: false },
  { number: 70, name: "Dark Bell", badge: "U", label: "Item \u00b7 Uncommon", holoTier: 0, secret: false },
  { number: 71, name: "Skull Fossil", badge: "C", label: "Item \u00b7 Common", holoTier: 0, secret: false },
  { number: 72, name: "Armor Fossil", badge: "C", label: "Item \u00b7 Common", holoTier: 0, secret: false },
  { number: 73, name: "Regret Bomb", badge: "U", label: "Item \u00b7 Uncommon", holoTier: 0, secret: false },
  { number: 74, name: "Retry Badge", badge: "U", label: "Item \u00b7 Uncommon", holoTier: 0, secret: false },
  { number: 75, name: "Misty's Energy", badge: "U", label: "Special Energy \u00b7 Uncommon", holoTier: 0, secret: false },
  { number: 76, name: "Gladion's Determination", badge: "U", label: "Supporter \u00b7 Uncommon", holoTier: 0, secret: false },
  { number: 77, name: "Faba's Underling", badge: "U", label: "Supporter \u00b7 Uncommon", holoTier: 0, secret: false },
  { number: 78, name: "Gwynn", badge: "U", label: "Supporter \u00b7 Uncommon", holoTier: 0, secret: false },
  { number: 79, name: "Fossil Dig Site", badge: "U", label: "Stadium \u00b7 Uncommon", holoTier: 0, secret: false },
  { number: 80, name: "Bolt Lightning Energy", badge: "R", label: "Special Energy \u00b7 Rare", holoTier: 1, secret: false },
  { number: 81, name: "Shadow Energy", badge: "R", label: "Special Energy \u00b7 Rare", holoTier: 1, secret: false },
  { number: 82, name: "Fomantis", badge: "AR", label: "Pok\u00e9mon \u00b7 Art Rare", holoTier: 2, secret: true },
  { number: 83, name: "Armarouge", badge: "AR", label: "Pok\u00e9mon \u00b7 Art Rare", holoTier: 2, secret: true },
  { number: 84, name: "Goldeen", badge: "AR", label: "Pok\u00e9mon \u00b7 Art Rare", holoTier: 2, secret: true },
  { number: 85, name: "Primarina", badge: "AR", label: "Pok\u00e9mon \u00b7 Art Rare", holoTier: 2, secret: true },
  { number: 86, name: "Manectric", badge: "AR", label: "Pok\u00e9mon \u00b7 Art Rare", holoTier: 2, secret: true },
  { number: 87, name: "Slowbro", badge: "AR", label: "Pok\u00e9mon \u00b7 Art Rare", holoTier: 2, secret: true },
  { number: 88, name: "Dhelmise", badge: "AR", label: "Pok\u00e9mon \u00b7 Art Rare", holoTier: 2, secret: true },
  { number: 89, name: "Thievul", badge: "AR", label: "Pok\u00e9mon \u00b7 Art Rare", holoTier: 2, secret: true },
  { number: 90, name: "Zarude", badge: "AR", label: "Pok\u00e9mon \u00b7 Art Rare", holoTier: 2, secret: true },
  { number: 91, name: "Bastiodon", badge: "AR", label: "Pok\u00e9mon \u00b7 Art Rare", holoTier: 2, secret: true },
  { number: 92, name: "Toucannon", badge: "AR", label: "Pok\u00e9mon \u00b7 Art Rare", holoTier: 2, secret: true },
  { number: 93, name: "Silvally", badge: "AR", label: "Pok\u00e9mon \u00b7 Art Rare", holoTier: 2, secret: true },
  { number: 94, name: "Lurantis ex", badge: "SR", label: "Pok\u00e9mon ex \u00b7 Super Rare", holoTier: 3, secret: true },
  { number: 95, name: "Wailord ex", badge: "SR", label: "Pok\u00e9mon ex \u00b7 Super Rare", holoTier: 3, secret: true },
  { number: 96, name: "Mega Zeraora ex", badge: "SR", label: "Mega ex \u00b7 Super Rare", holoTier: 3, secret: true },
  { number: 97, name: "Mega Chandelure ex", badge: "SR", label: "Mega ex \u00b7 Super Rare", holoTier: 3, secret: true },
  { number: 98, name: "Rampardos ex", badge: "SR", label: "Pok\u00e9mon ex \u00b7 Super Rare", holoTier: 3, secret: true },
  { number: 99, name: "Mega Darkrai ex", badge: "SR", label: "Mega ex \u00b7 Super Rare", holoTier: 3, secret: true },
  { number: 100, name: "Morpeko ex", badge: "SR", label: "Pok\u00e9mon ex \u00b7 Super Rare", holoTier: 3, secret: true },
  { number: 101, name: "Mega Excadrill ex", badge: "SR", label: "Mega ex \u00b7 Super Rare", holoTier: 3, secret: true },
  { number: 102, name: "Iron Defender", badge: "SR", label: "Item \u00b7 Super Rare", holoTier: 3, secret: true },
  { number: 103, name: "Energy Switch", badge: "SR", label: "Item \u00b7 Super Rare", holoTier: 3, secret: true },
  { number: 104, name: "Crushing Hammer", badge: "SR", label: "Item \u00b7 Super Rare", holoTier: 3, secret: true },
  { number: 105, name: "Dark Bell", badge: "SR", label: "Item \u00b7 Super Rare", holoTier: 3, secret: true },
  { number: 106, name: "Heroic Bomb", badge: "SR", label: "Item \u00b7 Super Rare", holoTier: 3, secret: true },
  { number: 107, name: "Brave Bangle", badge: "SR", label: "Item \u00b7 Super Rare", holoTier: 3, secret: true },
  { number: 108, name: "Misty's Energy", badge: "SR", label: "Special Energy \u00b7 Super Rare", holoTier: 3, secret: true },
  { number: 109, name: "Gladion's Fighting Spirit", badge: "SR", label: "Supporter \u00b7 Super Rare", holoTier: 3, secret: true },
  { number: 110, name: "Rust Syndicate Grunts", badge: "SR", label: "Supporter \u00b7 Super Rare", holoTier: 3, secret: true },
  { number: 111, name: "Gwynn", badge: "SR", label: "Supporter \u00b7 Super Rare", holoTier: 3, secret: true },
  { number: 112, name: "Mega Zeraora ex", badge: "SAR", label: "Mega ex \u00b7 Special Art Rare", holoTier: 4, secret: true },
  { number: 113, name: "Mega Chandelure ex", badge: "SAR", label: "Mega ex \u00b7 Special Art Rare", holoTier: 4, secret: true },
  { number: 114, name: "Mega Darkrai ex", badge: "SAR", label: "Mega ex \u00b7 Special Art Rare", holoTier: 4, secret: true },
  { number: 115, name: "Morpeko ex", badge: "SAR", label: "Pok\u00e9mon ex \u00b7 Special Art Rare", holoTier: 4, secret: true },
  { number: 116, name: "Gladion's Fighting Spirit", badge: "SAR", label: "Supporter \u00b7 Special Art Rare", holoTier: 4, secret: true },
  { number: 117, name: "Gwynn", badge: "SAR", label: "Supporter \u00b7 Special Art Rare", holoTier: 4, secret: true },
  { number: 118, name: "Mega Darkrai ex", badge: "MUR", label: "Mega ex \u00b7 Mega Ultra Rare", holoTier: 5, secret: true },
];
