// AUTO-GENERATED — Japanese names + rarities from Yuyu-tei (yuyu-tei.jp/sell/poc/s/m03).
import type { Card } from "./types";

export const munikisZeroCards: Card[] = [
  { number: 1, name: "イトマル", badge: "C", label: "Common", holoTier: 0, secret: false },
  { number: 2, name: "アリアドス", badge: "C", label: "Common", holoTier: 0, secret: false },
  { number: 3, name: "シェイミ", badge: "U", label: "Uncommon", holoTier: 0, secret: false },
  { number: 4, name: "ツタージャ", badge: "C", label: "Common", holoTier: 0, secret: false },
  { number: 5, name: "ジャノビー", badge: "C", label: "Common", holoTier: 0, secret: false },
  { number: 6, name: "ジャローダ", badge: "R", label: "Rare", holoTier: 1, secret: false },
  { number: 7, name: "コフキムシ", badge: "C", label: "Common", holoTier: 0, secret: false },
  { number: 8, name: "コフーライ", badge: "C", label: "Common", holoTier: 0, secret: false },
  { number: 9, name: "ビビヨン", badge: "U", label: "Uncommon", holoTier: 0, secret: false },
  { number: 10, name: "モクロー", badge: "C", label: "Common", holoTier: 0, secret: false },
  { number: 11, name: "フクスロー", badge: "C", label: "Common", holoTier: 0, secret: false },
  { number: 12, name: "ジュナイパーex", badge: "RR", label: "Pokémon ex · Double Rare", holoTier: 1, secret: false },
  { number: 13, name: "ヒノヤコマ", badge: "C", label: "Common", holoTier: 0, secret: false },
  { number: 14, name: "ファイアロー", badge: "U", label: "Uncommon", holoTier: 0, secret: false },
  { number: 15, name: "ヤトウモリ", badge: "C", label: "Common", holoTier: 0, secret: false },
  { number: 16, name: "エンニュートex", badge: "RR", label: "Pokémon ex · Double Rare", holoTier: 1, secret: false },
  { number: 17, name: "バクガメス", badge: "U", label: "Uncommon", holoTier: 0, secret: false },
  { number: 18, name: "パウワウ", badge: "C", label: "Common", holoTier: 0, secret: false },
  { number: 19, name: "ジュゴン", badge: "R", label: "Rare", holoTier: 1, secret: false },
  { number: 20, name: "ヒトデマン", badge: "C", label: "Common", holoTier: 0, secret: false },
  { number: 21, name: "メガスターミーex", badge: "RR", label: "Mega ex · Double Rare", holoTier: 1, secret: false },
  { number: 22, name: "アマルス", badge: "C", label: "Common", holoTier: 0, secret: false },
  { number: 23, name: "アマルルガ", badge: "U", label: "Uncommon", holoTier: 0, secret: false },
  { number: 24, name: "ボルケニオン", badge: "U", label: "Uncommon", holoTier: 0, secret: false },
  { number: 25, name: "コリンク", badge: "C", label: "Common", holoTier: 0, secret: false },
  { number: 26, name: "ルクシオ", badge: "U", label: "Uncommon", holoTier: 0, secret: false },
  { number: 27, name: "レントラー", badge: "R", label: "Rare", holoTier: 1, secret: false },
  { number: 28, name: "デデンネ", badge: "C", label: "Common", holoTier: 0, secret: false },
  { number: 29, name: "ピッピ", badge: "C", label: "Common", holoTier: 0, secret: false },
  { number: 30, name: "メガピクシーex", badge: "RR", label: "Mega ex · Double Rare", holoTier: 1, secret: false },
  { number: 31, name: "クチート", badge: "C", label: "Common", holoTier: 0, secret: false },
  { number: 32, name: "ニャスパー", badge: "C", label: "Common", holoTier: 0, secret: false },
  { number: 33, name: "ニャオニクス", badge: "U", label: "Uncommon", holoTier: 0, secret: false },
  { number: 34, name: "シュシュプ", badge: "C", label: "Common", holoTier: 0, secret: false },
  { number: 35, name: "フレフワン", badge: "U", label: "Uncommon", holoTier: 0, secret: false },
  { number: 36, name: "ノズパス", badge: "C", label: "Common", holoTier: 0, secret: false },
  { number: 37, name: "ダイノーズ", badge: "C", label: "Common", holoTier: 0, secret: false },
  { number: 38, name: "ヒポポタス", badge: "C", label: "Common", holoTier: 0, secret: false },
  { number: 39, name: "カバルドン", badge: "U", label: "Uncommon", holoTier: 0, secret: false },
  { number: 40, name: "ランドロス", badge: "R", label: "Rare", holoTier: 1, secret: false },
  { number: 41, name: "カメテテ", badge: "C", label: "Common", holoTier: 0, secret: false },
  { number: 42, name: "ガメノデス", badge: "U", label: "Uncommon", holoTier: 0, secret: false },
  { number: 43, name: "チゴラス", badge: "C", label: "Common", holoTier: 0, secret: false },
  { number: 44, name: "ガチゴラス", badge: "U", label: "Uncommon", holoTier: 0, secret: false },
  { number: 45, name: "ルチャブル", badge: "C", label: "Common", holoTier: 0, secret: false },
  { number: 46, name: "メガジガルデex", badge: "RR", label: "Mega ex · Double Rare", holoTier: 1, secret: false },
  { number: 47, name: "ゴース", badge: "C", label: "Common", holoTier: 0, secret: false },
  { number: 48, name: "ゴースト", badge: "C", label: "Common", holoTier: 0, secret: false },
  { number: 49, name: "ゲンガー", badge: "U", label: "Uncommon", holoTier: 0, secret: false },
  { number: 50, name: "スコルピ", badge: "C", label: "Common", holoTier: 0, secret: false },
  { number: 51, name: "ドラピオン", badge: "U", label: "Uncommon", holoTier: 0, secret: false },
  { number: 52, name: "イベルタルex", badge: "RR", label: "Pokémon ex · Double Rare", holoTier: 1, secret: false },
  { number: 53, name: "パオジアン", badge: "R", label: "Rare", holoTier: 1, secret: false },
  { number: 54, name: "メガエアームドex", badge: "RR", label: "Mega ex · Double Rare", holoTier: 1, secret: false },
  { number: 55, name: "ヒトツキ", badge: "C", label: "Common", holoTier: 0, secret: false },
  { number: 56, name: "ニダンギル", badge: "C", label: "Common", holoTier: 0, secret: false },
  { number: 57, name: "ギルガルド", badge: "U", label: "Uncommon", holoTier: 0, secret: false },
  { number: 58, name: "クレッフィ", badge: "C", label: "Common", holoTier: 0, secret: false },
  { number: 59, name: "コラッタ", badge: "C", label: "Common", holoTier: 0, secret: false },
  { number: 60, name: "ラッタ", badge: "U", label: "Uncommon", holoTier: 0, secret: false },
  { number: 61, name: "ニャースex", badge: "RR", label: "Pokémon ex · Double Rare", holoTier: 1, secret: false },
  { number: 62, name: "カビゴン", badge: "C", label: "Common", holoTier: 0, secret: false },
  { number: 63, name: "ホルビー", badge: "C", label: "Common", holoTier: 0, secret: false },
  { number: 64, name: "ホルード", badge: "U", label: "Uncommon", holoTier: 0, secret: false },
  { number: 65, name: "ヤヤコマ", badge: "C", label: "Common", holoTier: 0, secret: false },
  { number: 66, name: "トリミアン", badge: "C", label: "Common", holoTier: 0, secret: false },
  { number: 67, name: "エネはたき", badge: "U", label: "Uncommon", holoTier: 0, secret: false },
  { number: 68, name: "古びたアゴの化石", badge: "C", label: "Common", holoTier: 0, secret: false },
  { number: 69, name: "古びたヒレの化石", badge: "C", label: "Common", holoTier: 0, secret: false },
  { number: 70, name: "ポケパッド", badge: "U", label: "Uncommon", holoTier: 0, secret: false },
  { number: 71, name: "ミアレガレット", badge: "U", label: "Uncommon", holoTier: 0, secret: false },
  { number: 72, name: "コアメモリ", badge: "U", label: "Uncommon", holoTier: 0, secret: false },
  { number: 73, name: "タラゴン", badge: "U", label: "Uncommon", holoTier: 0, secret: false },
  { number: 74, name: "ピュール", badge: "U", label: "Uncommon", holoTier: 0, secret: false },
  { number: 75, name: "メイのはげまし", badge: "U", label: "Uncommon", holoTier: 0, secret: false },
  { number: 76, name: "ユカリ", badge: "U", label: "Uncommon", holoTier: 0, secret: false },
  { number: 77, name: "ミアレシティ", badge: "U", label: "Uncommon", holoTier: 0, secret: false },
  { number: 78, name: "グロウ草エネルギー", badge: "R", label: "Rare", holoTier: 1, secret: false },
  { number: 79, name: "テレパス超エネルギー", badge: "R", label: "Rare", holoTier: 1, secret: false },
  { number: 80, name: "ロック闘エネルギー", badge: "R", label: "Rare", holoTier: 1, secret: false },
  { number: 81, name: "コフーライ", badge: "AR", label: "Art Rare", holoTier: 2, secret: true },
  { number: 82, name: "モクロー", badge: "AR", label: "Art Rare", holoTier: 2, secret: true },
  { number: 83, name: "ファイアロー", badge: "AR", label: "Art Rare", holoTier: 2, secret: true },
  { number: 84, name: "アマルルガ", badge: "AR", label: "Art Rare", holoTier: 2, secret: true },
  { number: 85, name: "デデンネ", badge: "AR", label: "Art Rare", holoTier: 2, secret: true },
  { number: 86, name: "ピッピ", badge: "AR", label: "Art Rare", holoTier: 2, secret: true },
  { number: 87, name: "ニャスパー", badge: "AR", label: "Art Rare", holoTier: 2, secret: true },
  { number: 88, name: "ダイノーズ", badge: "AR", label: "Art Rare", holoTier: 2, secret: true },
  { number: 89, name: "チゴラス", badge: "AR", label: "Art Rare", holoTier: 2, secret: true },
  { number: 90, name: "ドラピオン", badge: "AR", label: "Art Rare", holoTier: 2, secret: true },
  { number: 91, name: "ニダンギル", badge: "AR", label: "Art Rare", holoTier: 2, secret: true },
  { number: 92, name: "ラッタ", badge: "AR", label: "Art Rare", holoTier: 2, secret: true },
  { number: 93, name: "ジュナイパーex", badge: "SR", label: "Pokémon ex · Super Rare", holoTier: 3, secret: true },
  { number: 94, name: "エンニュートex", badge: "SR", label: "Pokémon ex · Super Rare", holoTier: 3, secret: true },
  { number: 95, name: "メガスターミーex", badge: "SR", label: "Mega ex · Super Rare", holoTier: 3, secret: true },
  { number: 96, name: "メガピクシーex", badge: "SR", label: "Mega ex · Super Rare", holoTier: 3, secret: true },
  { number: 97, name: "メガジガルデex", badge: "SR", label: "Mega ex · Super Rare", holoTier: 3, secret: true },
  { number: 98, name: "イベルタルex", badge: "SR", label: "Pokémon ex · Super Rare", holoTier: 3, secret: true },
  { number: 99, name: "メガエアームドex", badge: "SR", label: "Mega ex · Super Rare", holoTier: 3, secret: true },
  { number: 100, name: "ニャースex", badge: "SR", label: "Pokémon ex · Super Rare", holoTier: 3, secret: true },
  { number: 101, name: "エネルギーリサイクル", badge: "SR", label: "Super Rare", holoTier: 3, secret: true },
  { number: 102, name: "せいなるはい", badge: "SR", label: "Super Rare", holoTier: 3, secret: true },
  { number: 103, name: "ポケパッド", badge: "SR", label: "Super Rare", holoTier: 3, secret: true },
  { number: 104, name: "ワンダーパッチ", badge: "SR", label: "Super Rare", holoTier: 3, secret: true },
  { number: 105, name: "タラゴン", badge: "SR", label: "Super Rare", holoTier: 3, secret: true },
  { number: 106, name: "ピュール", badge: "SR", label: "Super Rare", holoTier: 3, secret: true },
  { number: 107, name: "メイのはげまし", badge: "SR", label: "Super Rare", holoTier: 3, secret: true },
  { number: 108, name: "ユカリ", badge: "SR", label: "Super Rare", holoTier: 3, secret: true },
  { number: 109, name: "活力の森", badge: "SR", label: "Super Rare", holoTier: 3, secret: true },
  { number: 110, name: "ミアレシティ", badge: "SR", label: "Super Rare", holoTier: 3, secret: true },
  { number: 111, name: "メガスターミーex", badge: "SAR", label: "Mega ex · Special Art Rare", holoTier: 4, secret: true },
  { number: 112, name: "メガピクシーex", badge: "SAR", label: "Mega ex · Special Art Rare", holoTier: 4, secret: true },
  { number: 113, name: "メガジガルデex", badge: "SAR", label: "Mega ex · Special Art Rare", holoTier: 4, secret: true },
  { number: 114, name: "ニャースex", badge: "SAR", label: "Pokémon ex · Special Art Rare", holoTier: 4, secret: true },
  { number: 115, name: "メイのはげまし", badge: "SAR", label: "Special Art Rare", holoTier: 4, secret: true },
  { number: 116, name: "ユカリ", badge: "SAR", label: "Special Art Rare", holoTier: 4, secret: true },
  { number: 117, name: "メガジガルデex", badge: "MUR", label: "Mega ex · Mega Ultra Rare", holoTier: 5, secret: true },
];
