// AUTO-GENERATED — names/kinds from public/pdfs/Ninja_Spinner_binder_inserts.pdf,
// rarities from Yuyu-tei (yuyu-tei.jp/sell/poc/s/m04). Matches the Abyss Eye shape.

import type { Card } from "./types";

export const ninjaSpinnerCards: Card[] = [
  { number: 1, name: "Weedle", badge: "C", label: "Pok\u00e9mon \u00b7 Common", holoTier: 0, secret: false },
  { number: 2, name: "Kakuna", badge: "C", label: "Pok\u00e9mon \u00b7 Common", holoTier: 0, secret: false },
  { number: 3, name: "Beedrill ex", badge: "RR", label: "Pok\u00e9mon ex \u00b7 Double Rare", holoTier: 1, secret: false },
  { number: 4, name: "Carnivine", badge: "C", label: "Pok\u00e9mon \u00b7 Common", holoTier: 0, secret: false },
  { number: 5, name: "Chespin", badge: "C", label: "Pok\u00e9mon \u00b7 Common", holoTier: 0, secret: false },
  { number: 6, name: "Quilladin", badge: "C", label: "Pok\u00e9mon \u00b7 Common", holoTier: 0, secret: false },
  { number: 7, name: "Chesnaught", badge: "R", label: "Pok\u00e9mon \u00b7 Rare", holoTier: 1, secret: false },
  { number: 8, name: "Vulpix", badge: "C", label: "Pok\u00e9mon \u00b7 Common", holoTier: 0, secret: false },
  { number: 9, name: "Ninetales", badge: "U", label: "Pok\u00e9mon \u00b7 Uncommon", holoTier: 0, secret: false },
  { number: 10, name: "Ho-Oh", badge: "U", label: "Pok\u00e9mon \u00b7 Uncommon", holoTier: 0, secret: false },
  { number: 11, name: "Fennekin", badge: "C", label: "Pok\u00e9mon \u00b7 Common", holoTier: 0, secret: false },
  { number: 12, name: "Braixen", badge: "C", label: "Pok\u00e9mon \u00b7 Common", holoTier: 0, secret: false },
  { number: 13, name: "Delphox", badge: "R", label: "Pok\u00e9mon \u00b7 Rare", holoTier: 1, secret: false },
  { number: 14, name: "Litleo", badge: "C", label: "Pok\u00e9mon \u00b7 Common", holoTier: 0, secret: false },
  { number: 15, name: "Mega Pyroar ex", badge: "RR", label: "Mega ex \u00b7 Double Rare", holoTier: 1, secret: false },
  { number: 16, name: "Remoraid", badge: "C", label: "Pok\u00e9mon \u00b7 Common", holoTier: 0, secret: false },
  { number: 17, name: "Octillery", badge: "C", label: "Pok\u00e9mon \u00b7 Common", holoTier: 0, secret: false },
  { number: 18, name: "Delibird", badge: "U", label: "Pok\u00e9mon \u00b7 Uncommon", holoTier: 0, secret: false },
  { number: 19, name: "Keldeo", badge: "U", label: "Pok\u00e9mon \u00b7 Uncommon", holoTier: 0, secret: false },
  { number: 20, name: "Froakie", badge: "C", label: "Pok\u00e9mon \u00b7 Common", holoTier: 0, secret: false },
  { number: 21, name: "Frogadier", badge: "C", label: "Pok\u00e9mon \u00b7 Common", holoTier: 0, secret: false },
  { number: 22, name: "Mega Greninja ex", badge: "RR", label: "Mega ex \u00b7 Double Rare", holoTier: 1, secret: false },
  { number: 23, name: "Bergmite", badge: "C", label: "Pok\u00e9mon \u00b7 Common", holoTier: 0, secret: false },
  { number: 24, name: "Avalugg", badge: "U", label: "Pok\u00e9mon \u00b7 Uncommon", holoTier: 0, secret: false },
  { number: 25, name: "Wimpod", badge: "C", label: "Pok\u00e9mon \u00b7 Common", holoTier: 0, secret: false },
  { number: 26, name: "Golisopod", badge: "U", label: "Pok\u00e9mon \u00b7 Uncommon", holoTier: 0, secret: false },
  { number: 27, name: "Mareep", badge: "C", label: "Pok\u00e9mon \u00b7 Common", holoTier: 0, secret: false },
  { number: 28, name: "Flaaffy", badge: "C", label: "Pok\u00e9mon \u00b7 Common", holoTier: 0, secret: false },
  { number: 29, name: "Ampharos", badge: "R", label: "Pok\u00e9mon \u00b7 Rare", holoTier: 1, secret: false },
  { number: 30, name: "Emolga", badge: "C", label: "Pok\u00e9mon \u00b7 Common", holoTier: 0, secret: false },
  { number: 31, name: "Deoxys", badge: "U", label: "Pok\u00e9mon \u00b7 Uncommon", holoTier: 0, secret: false },
  { number: 32, name: "Deoxys", badge: "U", label: "Pok\u00e9mon \u00b7 Uncommon", holoTier: 0, secret: false },
  { number: 33, name: "Deoxys", badge: "U", label: "Pok\u00e9mon \u00b7 Uncommon", holoTier: 0, secret: false },
  { number: 34, name: "Deoxys", badge: "U", label: "Pok\u00e9mon \u00b7 Uncommon", holoTier: 0, secret: false },
  { number: 35, name: "Mega Floette ex", badge: "RR", label: "Mega ex \u00b7 Double Rare", holoTier: 1, secret: false },
  { number: 36, name: "Espurr", badge: "C", label: "Pok\u00e9mon \u00b7 Common", holoTier: 0, secret: false },
  { number: 37, name: "Meowstic", badge: "U", label: "Pok\u00e9mon \u00b7 Uncommon", holoTier: 0, secret: false },
  { number: 38, name: "Phantump", badge: "C", label: "Pok\u00e9mon \u00b7 Common", holoTier: 0, secret: false },
  { number: 39, name: "Trevenant", badge: "R", label: "Pok\u00e9mon \u00b7 Rare", holoTier: 1, secret: false },
  { number: 40, name: "Pumpkaboo", badge: "C", label: "Pok\u00e9mon \u00b7 Common", holoTier: 0, secret: false },
  { number: 41, name: "Gourgeist ex", badge: "RR", label: "Pok\u00e9mon ex \u00b7 Double Rare", holoTier: 1, secret: false },
  { number: 42, name: "Xerneas", badge: "R", label: "Pok\u00e9mon \u00b7 Rare", holoTier: 1, secret: false },
  { number: 43, name: "Sudowoodo", badge: "U", label: "Pok\u00e9mon \u00b7 Uncommon", holoTier: 0, secret: false },
  { number: 44, name: "Phanpy", badge: "C", label: "Pok\u00e9mon \u00b7 Common", holoTier: 0, secret: false },
  { number: 45, name: "Donphan", badge: "C", label: "Pok\u00e9mon \u00b7 Common", holoTier: 0, secret: false },
  { number: 46, name: "Baltoy", badge: "C", label: "Pok\u00e9mon \u00b7 Common", holoTier: 0, secret: false },
  { number: 47, name: "Claydol", badge: "U", label: "Pok\u00e9mon \u00b7 Uncommon", holoTier: 0, secret: false },
  { number: 48, name: "Zubat", badge: "C", label: "Pok\u00e9mon \u00b7 Common", holoTier: 0, secret: false },
  { number: 49, name: "Golbat", badge: "C", label: "Pok\u00e9mon \u00b7 Common", holoTier: 0, secret: false },
  { number: 50, name: "Crobat", badge: "U", label: "Pok\u00e9mon \u00b7 Uncommon", holoTier: 0, secret: false },
  { number: 51, name: "Qwilfish", badge: "C", label: "Pok\u00e9mon \u00b7 Common", holoTier: 0, secret: false },
  { number: 52, name: "Stunky", badge: "C", label: "Pok\u00e9mon \u00b7 Common", holoTier: 0, secret: false },
  { number: 53, name: "Skuntank", badge: "U", label: "Pok\u00e9mon \u00b7 Uncommon", holoTier: 0, secret: false },
  { number: 54, name: "Trubbish", badge: "C", label: "Pok\u00e9mon \u00b7 Common", holoTier: 0, secret: false },
  { number: 55, name: "Garbodor", badge: "U", label: "Pok\u00e9mon \u00b7 Uncommon", holoTier: 0, secret: false },
  { number: 56, name: "Skrelp", badge: "C", label: "Pok\u00e9mon \u00b7 Common", holoTier: 0, secret: false },
  { number: 57, name: "Beldum", badge: "C", label: "Pok\u00e9mon \u00b7 Common", holoTier: 0, secret: false },
  { number: 58, name: "Metang", badge: "C", label: "Pok\u00e9mon \u00b7 Common", holoTier: 0, secret: false },
  { number: 59, name: "Metagross", badge: "U", label: "Pok\u00e9mon \u00b7 Uncommon", holoTier: 0, secret: false },
  { number: 60, name: "Ferroseed", badge: "C", label: "Pok\u00e9mon \u00b7 Common", holoTier: 0, secret: false },
  { number: 61, name: "Ferrothorn", badge: "U", label: "Pok\u00e9mon \u00b7 Uncommon", holoTier: 0, secret: false },
  { number: 62, name: "Cobalion ex", badge: "RR", label: "Pok\u00e9mon ex \u00b7 Double Rare", holoTier: 1, secret: false },
  { number: 63, name: "Mega Dragalge ex", badge: "RR", label: "Mega ex \u00b7 Double Rare", holoTier: 1, secret: false },
  { number: 64, name: "Goomy", badge: "C", label: "Pok\u00e9mon \u00b7 Common", holoTier: 0, secret: false },
  { number: 65, name: "Sliggoo", badge: "C", label: "Pok\u00e9mon \u00b7 Common", holoTier: 0, secret: false },
  { number: 66, name: "Goodra", badge: "U", label: "Pok\u00e9mon \u00b7 Uncommon", holoTier: 0, secret: false },
  { number: 67, name: "Tauros", badge: "U", label: "Pok\u00e9mon \u00b7 Uncommon", holoTier: 0, secret: false },
  { number: 68, name: "Patrat", badge: "C", label: "Pok\u00e9mon \u00b7 Common", holoTier: 0, secret: false },
  { number: 69, name: "Watchog", badge: "C", label: "Pok\u00e9mon \u00b7 Common", holoTier: 0, secret: false },
  { number: 70, name: "Minccino", badge: "C", label: "Pok\u00e9mon \u00b7 Common", holoTier: 0, secret: false },
  { number: 71, name: "Cinccino ex", badge: "RR", label: "Pok\u00e9mon ex \u00b7 Double Rare", holoTier: 1, secret: false },
  { number: 72, name: "Special Red Card", badge: "U", label: "Trainer \u00b7 Item \u00b7 Uncommon", holoTier: 0, secret: false },
  { number: 73, name: "Big Catching Net", badge: "U", label: "Trainer \u00b7 Item \u00b7 Uncommon", holoTier: 0, secret: false },
  { number: 74, name: "Tomes of Transformation", badge: "U", label: "Trainer \u00b7 Item \u00b7 Uncommon", holoTier: 0, secret: false },
  { number: 75, name: "AZ's Tranquility", badge: "U", label: "Trainer \u00b7 Supporter \u00b7 Uncommon", holoTier: 0, secret: false },
  { number: 76, name: "Philippe", badge: "U", label: "Trainer \u00b7 Supporter \u00b7 Uncommon", holoTier: 0, secret: false },
  { number: 77, name: "Roxie's Performance", badge: "U", label: "Trainer \u00b7 Supporter \u00b7 Uncommon", holoTier: 0, secret: false },
  { number: 78, name: "Emma", badge: "U", label: "Trainer \u00b7 Supporter \u00b7 Uncommon", holoTier: 0, secret: false },
  { number: 79, name: "Ange Floette", badge: "U", label: "Trainer \u00b7 Stadium \u00b7 Uncommon", holoTier: 0, secret: false },
  { number: 80, name: "Prism Tower", badge: "U", label: "Trainer \u00b7 Stadium \u00b7 Uncommon", holoTier: 0, secret: false },
  { number: 81, name: "Nitro Fire Energy", badge: "R", label: "Special Energy \u00b7 Rare", holoTier: 1, secret: false },
  { number: 82, name: "Bubble Water Energy", badge: "R", label: "Special Energy \u00b7 Rare", holoTier: 1, secret: false },
  { number: 83, name: "Magnet Metal Energy", badge: "R", label: "Special Energy \u00b7 Rare", holoTier: 1, secret: false },
  { number: 84, name: "Chespin", badge: "AR", label: "Pok\u00e9mon \u00b7 Art Rare", holoTier: 2, secret: true },
  { number: 85, name: "Fennekin", badge: "AR", label: "Pok\u00e9mon \u00b7 Art Rare", holoTier: 2, secret: true },
  { number: 86, name: "Froakie", badge: "AR", label: "Pok\u00e9mon \u00b7 Art Rare", holoTier: 2, secret: true },
  { number: 87, name: "Frogadier", badge: "AR", label: "Pok\u00e9mon \u00b7 Art Rare", holoTier: 2, secret: true },
  { number: 88, name: "Ampharos", badge: "AR", label: "Pok\u00e9mon \u00b7 Art Rare", holoTier: 2, secret: true },
  { number: 89, name: "Xerneas", badge: "AR", label: "Pok\u00e9mon \u00b7 Art Rare", holoTier: 2, secret: true },
  { number: 90, name: "Claydol", badge: "AR", label: "Pok\u00e9mon \u00b7 Art Rare", holoTier: 2, secret: true },
  { number: 91, name: "Crobat", badge: "AR", label: "Pok\u00e9mon \u00b7 Art Rare", holoTier: 2, secret: true },
  { number: 92, name: "Metang", badge: "AR", label: "Pok\u00e9mon \u00b7 Art Rare", holoTier: 2, secret: true },
  { number: 93, name: "Sliggoo", badge: "AR", label: "Pok\u00e9mon \u00b7 Art Rare", holoTier: 2, secret: true },
  { number: 94, name: "Tauros", badge: "AR", label: "Pok\u00e9mon \u00b7 Art Rare", holoTier: 2, secret: true },
  { number: 95, name: "Watchog", badge: "AR", label: "Pok\u00e9mon \u00b7 Art Rare", holoTier: 2, secret: true },
  { number: 96, name: "Beedrill ex", badge: "SR", label: "Pok\u00e9mon ex \u00b7 Super Rare", holoTier: 3, secret: true },
  { number: 97, name: "Mega Pyroar ex", badge: "SR", label: "Mega ex \u00b7 Super Rare", holoTier: 3, secret: true },
  { number: 98, name: "Mega Greninja ex", badge: "SR", label: "Mega ex \u00b7 Super Rare", holoTier: 3, secret: true },
  { number: 99, name: "Mega Floette ex", badge: "SR", label: "Mega ex \u00b7 Super Rare", holoTier: 3, secret: true },
  { number: 100, name: "Gourgeist ex", badge: "SR", label: "Pok\u00e9mon ex \u00b7 Super Rare", holoTier: 3, secret: true },
  { number: 101, name: "Cobalion ex", badge: "SR", label: "Pok\u00e9mon ex \u00b7 Super Rare", holoTier: 3, secret: true },
  { number: 102, name: "Mega Dragalge ex", badge: "SR", label: "Mega ex \u00b7 Super Rare", holoTier: 3, secret: true },
  { number: 103, name: "Cinccino ex", badge: "SR", label: "Pok\u00e9mon ex \u00b7 Super Rare", holoTier: 3, secret: true },
  { number: 104, name: "Energy Retrieval", badge: "SR", label: "Trainer \u00b7 Item \u00b7 Super Rare", holoTier: 3, secret: true },
  { number: 105, name: "Jumbo Ice Cream", badge: "SR", label: "Trainer \u00b7 Item \u00b7 Super Rare", holoTier: 3, secret: true },
  { number: 106, name: "Special Red Card", badge: "SR", label: "Trainer \u00b7 Item \u00b7 Super Rare", holoTier: 3, secret: true },
  { number: 107, name: "Tool Scrapper", badge: "SR", label: "Trainer \u00b7 Item \u00b7 Super Rare", holoTier: 3, secret: true },
  { number: 108, name: "AZ's Tranquility", badge: "SR", label: "Trainer \u00b7 Supporter \u00b7 Super Rare", holoTier: 3, secret: true },
  { number: 109, name: "Philippe", badge: "SR", label: "Trainer \u00b7 Supporter \u00b7 Super Rare", holoTier: 3, secret: true },
  { number: 110, name: "Roxie's Performance", badge: "SR", label: "Trainer \u00b7 Supporter \u00b7 Super Rare", holoTier: 3, secret: true },
  { number: 111, name: "Emma", badge: "SR", label: "Trainer \u00b7 Supporter \u00b7 Super Rare", holoTier: 3, secret: true },
  { number: 112, name: "Surfing Beach", badge: "SR", label: "Trainer \u00b7 Stadium \u00b7 Super Rare", holoTier: 3, secret: true },
  { number: 113, name: "Prism Tower", badge: "SR", label: "Trainer \u00b7 Stadium \u00b7 Super Rare", holoTier: 3, secret: true },
  { number: 114, name: "Mega Greninja ex", badge: "SAR", label: "Mega ex \u00b7 Special Art Rare", holoTier: 4, secret: true },
  { number: 115, name: "Mega Floette ex", badge: "SAR", label: "Mega ex \u00b7 Special Art Rare", holoTier: 4, secret: true },
  { number: 116, name: "Mega Dragalge ex", badge: "SAR", label: "Mega ex \u00b7 Special Art Rare", holoTier: 4, secret: true },
  { number: 117, name: "Cinccino ex", badge: "SAR", label: "Pok\u00e9mon ex \u00b7 Special Art Rare", holoTier: 4, secret: true },
  { number: 118, name: "AZ's Tranquility", badge: "SAR", label: "Trainer \u00b7 Supporter \u00b7 Special Art Rare", holoTier: 4, secret: true },
  { number: 119, name: "Roxie's Performance", badge: "SAR", label: "Trainer \u00b7 Supporter \u00b7 Special Art Rare", holoTier: 4, secret: true },
  { number: 120, name: "Mega Greninja ex", badge: "MUR", label: "Mega ex \u00b7 Mega Ultra Rare", holoTier: 5, secret: true },
];
